### ISSUE TITLE
Extension fails to load

### ISSUE THREAD

**Issue by g0t4** [docker/docker-ai#3]
When this extension loads, I am prompted with the error: `Docker AI requires at least 10% of your local volume space to be reclaimable. See docker system df`

**Comment by doggy8088** [comment]
I've got the same error too. It probably a bug in the logic.

I'm using Docker Desktop `4.28.0` (139021) on Windows. Docker Engine `25.0.3`. Use `WSL2` as backend.

![image](https://github.com/docker/docker-ai/assets/88981/26903144-1c34-4573-9d9f-3f8fdd75f362)

Here is my result of `docker system df --format json`:

```json
{"Active":"3","Reclaimable":"37.68GB (97%)","Size":"38.69GB","TotalCount":"28","Type":"Images"}
{"Active":"3","Reclaimable":"0B (0%)","Size":"469.9MB","TotalCount":"3","Type":"Containers"}
{"Active":"2","Reclaimable":"173.4MB (2%)","Size":"5.888GB","TotalCount":"3","Type":"Local Volumes"}
{"Active":"0","Reclaimable":"455.7MB","Size":"455.7MB","TotalCount":"113","Type":"Build Cache"}
```

![image](https://github.com/docker/docker-ai/assets/88981/cefbbdf9-6bc6-4941-b206-1907a73d7753)

My **Local Volumes** never larger than `10%` when I'm running a container that use a volume which used up to the upper limit of the already claimed size. The `Size` will expanded automatically on Windows, so that the `Reclaimable` will always under `10%` and that will lead the condition will never be match. 

When I remove all my containers, the `Reclaimable` of the **Local Volumes** become 100%. 

I can't find a way to increase the `Reclaimable` value of total **Local Volumes**. I can't set quota of a volume on Windows. It's not supported.

**Comment by ColinMcNeil** [comment]
Closed as this feature has been removed.
